    <!--エラー文-->

    <% if book.errors.any? %>
      <div id=“error_explanation”>
        <h5><%= book.errors.count %>件のerrorが発生しました。</h5>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <!--左側の上側-->

    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no-image.jpg", size: "100x100" %>
      　<table class="table">
          <tbody>
            <tr>
          	  <th>name</th>
          	  <th><%= user.name %></th>
            </tr>
            <tr>
          	  <th>introduction</th>
          	  <th><%= user.introduction %></th>
            </tr>
        　 </tbody>
      　</table>

      <div class="row">
       <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
      </div>

      <!--左の下側-->

      <h2>New book</h2>


      <%= form_with model: book, url: books_path, local: true do |f|%>

        <div class="field row">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
        </div>

        <div class="field row">
          <%= f.label :Opinion %><br>
          <%= f.text_field :body, class: "col-xs-12 book_body" %>
        </div>

        <div class="actions row">
          <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
        </div>

      <% end %>
    </div>
